# Generated by Django 3.2.7 on 2022-08-19 16:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220819_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Washington DC', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country'),
        ),
    ]
